/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth sign-in flow */
        get: operations["AuthController_googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback endpoint */
        get: operations["AuthController_googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out current user */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["UserController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign role to a user */
        patch: operations["UserController_assignRole"];
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List questions (paginated, filterable, sortable) */
        get: operations["QuestionController_findAll"];
        put?: never;
        /** Create question */
        post: operations["QuestionController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Faceted counts for the picker sidebar
         * @description Returns each filter facet (difficulty / category / subcategory / role / tags) with a per-value count. Counts respect every other filter on the request so the user sees what is still available before clicking.
         */
        get: operations["QuestionController_getFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get question by id */
        get: operations["QuestionController_findOne"];
        put?: never;
        post?: never;
        /** Soft delete question */
        delete: operations["QuestionController_remove"];
        options?: never;
        head?: never;
        /** Update question */
        patch: operations["QuestionController_update"];
        trace?: never;
    };
    "/questions/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find similar questions */
        post: operations["QuestionController_findSimilar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft delete questions in bulk */
        post: operations["QuestionController_bulkRemove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restore soft deleted question */
        patch: operations["QuestionController_restore"];
        trace?: never;
    };
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List interviews */
        get: operations["InterviewController_findAll"];
        put?: never;
        /** Create interview */
        post: operations["InterviewController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get interview by id */
        get: operations["InterviewController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update pending interview */
        patch: operations["InterviewController_update"];
        trace?: never;
    };
    "/interviews/{id}/candidate-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate candidate interview link */
        post: operations["InterviewController_generateCandidateLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel pending interview */
        patch: operations["InterviewController_cancel"];
        trace?: never;
    };
    "/interviews/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Complete interview */
        patch: operations["InterviewController_complete"];
        trace?: never;
    };
    "/interviews/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start validation for all submitted answers */
        post: operations["InterviewController_validateAllAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/questions/{questionIndex}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start validation for single answer */
        post: operations["InterviewController_validateAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get interview results */
        get: operations["InterviewController_getResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate one-shot upload URL */
        post: operations["UploadController_presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm one-shot upload */
        post: operations["UploadController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/multipart/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start multipart upload session */
        post: operations["UploadController_startMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/multipart/part": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign multipart upload part */
        post: operations["UploadController_presignMultipartPart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/multipart/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete multipart upload session */
        post: operations["UploadController_completeMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/multipart/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort multipart upload session */
        post: operations["UploadController_abortMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/questions/{questionIndex}/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate presigned URL for recruiter manual answer upload */
        post: operations["RecruiterMediaController_presignManualUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/questions/{questionIndex}/complete-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm recruiter manual answer upload */
        post: operations["RecruiterMediaController_completeManualUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/questions/{questionIndex}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get signed media URLs for interview answer */
        get: operations["RecruiterMediaController_getAnswerMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/take/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get candidate interview state */
        get: operations["TakeController_getInterview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/take/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit candidate answer */
        post: operations["TakeController_submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/take/{id}/answer/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save candidate answer progress */
        post: operations["TakeController_saveAnswerProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/take/{id}/questions/{questionIndex}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start candidate answer validation */
        post: operations["TakeController_startAnswerValidation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Candidate chat assistant */
        post: operations["AiController_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/greet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Candidate greeting prompt */
        post: operations["AiController_greet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/question-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate draft question with AI */
        post: operations["AiController_draftQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get interview feedback using a share link */
        get: operations["FeedbackController_getFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/feedback-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a shareable feedback link for an interview */
        post: operations["FeedbackLinkController_createLink"];
        /** Revoke the active shareable feedback link */
        delete: operations["FeedbackLinkController_revokeLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example admin@interview-app.com */
            email: string;
            /** @example admin123 */
            password: string;
        };
        AuthUserResponseDto: {
            /** @example 8d2a6457-7f4b-4cef-9f10-8cff885f7e15 */
            id: string;
            /** @example admin@interview-app.com */
            email: string;
            /** @example Super Admin */
            name: string;
            /** @example super_admin */
            role: string;
            /** @example org_123 */
            organizationId?: string;
            /**
             * Format: date-time
             * @example 2026-05-05T12:00:00.000Z
             */
            createdAt: string;
        };
        RegisterDto: {
            email: string;
            name: string;
            password: string;
        };
        LogoutResponseDto: {
            /** @example true */
            ok: boolean;
        };
        ApiErrorResponseDto: {
            /** @example 400 */
            statusCode: number;
            /** @example Bad Request */
            error: string;
            /** @example Validation failed */
            message: string | string[];
            /** @example /questions/invalid-id */
            path?: string;
        };
        AssignRoleDto: {
            /** @enum {string} */
            role: "super_admin" | "admin" | "hr" | "candidate";
        };
        QuestionExpectedConceptDto: {
            id: string;
            label: string;
            weight: number;
            description: string;
        };
        QuestionRedFlagDto: {
            id: string;
            label: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
        };
        QuestionResponseDto: {
            id: string;
            externalId?: string;
            role?: string;
            focus?: string;
            outputLanguage: string;
            category?: string;
            subcategory?: string;
            questionText: string;
            followUpQuestions: string[];
            expectedConcepts: components["schemas"]["QuestionExpectedConceptDto"][];
            redFlags: components["schemas"]["QuestionRedFlagDto"][];
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            weight: number;
            sampleGoodAnswer?: string;
            minimumPassScore: number;
            tags: string[];
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            deleted: boolean;
            /** @description True when deletion is scheduled because the question is still used by active interviews. */
            pendingDeletion: boolean;
            /** @description Number of times this question has been used in an interview. */
            usageCount: number;
        };
        PaginatedQuestionsResponseDto: {
            items: components["schemas"]["QuestionResponseDto"][];
            /** @description Total rows matching the filter, ignoring page/limit. */
            total: number;
            page: number;
            limit: number;
        };
        FacetCountDto: {
            value: string;
            /** @description Number of active questions with this value, given the rest of the current filters. */
            count: number;
        };
        QuestionFacetsResponseDto: {
            /** @description Difficulty value + count, given all OTHER current filters (difficulty itself is not applied). */
            difficulties: components["schemas"]["FacetCountDto"][];
            /** @description Category value + count, given all OTHER current filters (category itself is not applied). */
            categories: components["schemas"]["FacetCountDto"][];
            /** @description Subcategory value + count, given all OTHER current filters (subcategory itself is not applied). Exposed as the "Type" facet in the picker. */
            subcategories: components["schemas"]["FacetCountDto"][];
            /** @description Role value + count, given all OTHER current filters (role itself is not applied). */
            roles: components["schemas"]["FacetCountDto"][];
            /** @description Tag value + count, given all OTHER current filters (tag overlap is not applied). */
            tags: components["schemas"]["FacetCountDto"][];
        };
        CreateQuestionDto: {
            externalId?: string;
            role?: string;
            focus?: string;
            outputLanguage?: string;
            category?: string;
            subcategory?: string;
            questionText: string;
            followUpQuestions?: string[];
            expectedConcepts?: (string | components["schemas"]["QuestionExpectedConceptDto"])[];
            redFlags?: (string | components["schemas"]["QuestionRedFlagDto"])[];
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            weight?: number;
            sampleGoodAnswer?: string;
            minimumPassScore?: number;
            tags?: string[];
            metadata?: {
                [key: string]: unknown;
            };
        };
        FindSimilarDraftDto: {
            questionText?: string;
            category?: string;
            subcategory?: string;
            role?: string;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
        };
        FindSimilarDto: {
            draft?: components["schemas"]["FindSimilarDraftDto"];
            limit?: number;
            excludeQuestionId?: string;
        };
        SimilarQuestionMatchDto: {
            question: components["schemas"]["QuestionResponseDto"];
            score: number;
            reasons: string[];
        };
        FindSimilarResponseDto: {
            matches: components["schemas"]["SimilarQuestionMatchDto"][];
        };
        UpdateQuestionDto: {
            externalId?: string;
            role?: string;
            focus?: string;
            outputLanguage?: string;
            category?: string;
            subcategory?: string;
            questionText?: string;
            followUpQuestions?: string[];
            expectedConcepts?: (string | components["schemas"]["QuestionExpectedConceptDto"])[];
            redFlags?: (string | components["schemas"]["QuestionRedFlagDto"])[];
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            weight?: number;
            sampleGoodAnswer?: string;
            minimumPassScore?: number;
            tags?: string[];
            metadata?: {
                [key: string]: unknown;
            };
        };
        QuestionDeleteBlockingInterviewDto: {
            id: string;
            candidateName: string;
            /**
             * @description Staff app path to open the blocking interview.
             * @example /interviews/550e8400-e29b-41d4-a716-446655440000
             */
            href: string;
        };
        DeleteQuestionResponseDto: {
            id: string;
            /** @example true */
            deleted?: boolean;
            /** @example true */
            scheduled?: boolean;
            blockingInterviews?: components["schemas"]["QuestionDeleteBlockingInterviewDto"][];
        };
        BulkDeleteQuestionsDto: {
            ids: string[];
        };
        BulkDeleteScheduledItemDto: {
            id: string;
            questionText: string;
            reason: string;
            blockingInterviews: components["schemas"]["QuestionDeleteBlockingInterviewDto"][];
        };
        BulkDeleteQuestionsResponseDto: {
            deleted: string[];
            scheduled: components["schemas"]["BulkDeleteScheduledItemDto"][];
        };
        CreateInterviewDto: {
            candidateName: string;
            candidateEmail?: string;
            position: string;
            questionIds: string[];
        };
        MediaArtifactDto: {
            mediaKey: string;
            contentType: string;
            fileSizeBytes?: number;
            /** Format: date-time */
            uploadedAt: string;
        };
        AnswerBehaviorSignalsDto: {
            tabHiddenCount: number;
            windowBlurCount: number;
            pasteCount: number;
            keydownCount: number;
            copyCount: number;
            resizeCount: number;
        };
        AnswerTranscriptDto: {
            text?: string;
            language?: string;
            provider?: string;
            /** Format: date-time */
            generatedAt?: string;
            isFinal?: boolean;
        };
        AnswerEvaluationDto: {
            overallScore?: number;
            categoryScores?: {
                [key: string]: number;
            };
            coveredConceptIds?: string[];
            missedConceptIds?: string[];
            redFlagIds?: string[];
            /** @enum {string} */
            behaviorRisk?: "low" | "medium" | "high";
            summary?: string;
            /** @enum {string} */
            decisionHint?: "pass" | "review" | "fail";
            /** Format: date-time */
            evaluatedAt?: string;
        };
        AnswerValidationDto: {
            /** @enum {string} */
            status: "idle" | "queued" | "processing" | "completed" | "failed";
            executionArn?: string;
            sourceVersionNumber?: number;
            /** Format: date-time */
            requestedAt?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            errorMessage?: string;
        };
        AnswerBehaviorEventDto: {
            /** @enum {string} */
            eventType: "tab_hidden" | "window_blur" | "copy" | "paste" | "keydown" | "resize";
            /** Format: date-time */
            occurredAt: string;
            versionNumber: number;
        };
        AnswerVersionDto: {
            versionNumber: number;
            mediaKey: string;
            screenMediaKey?: string;
            /** Format: date-time */
            uploadedAt: string;
            durationSeconds?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            camera?: components["schemas"]["MediaArtifactDto"];
            screen?: components["schemas"]["MediaArtifactDto"];
            behaviorSignals?: components["schemas"]["AnswerBehaviorSignalsDto"];
            behaviorEvents?: components["schemas"]["AnswerBehaviorEventDto"][];
        };
        AnswerDto: {
            questionIndex: number;
            questionId: string;
            /** @enum {string} */
            status: "recording" | "submitted";
            mediaKey: string;
            screenMediaKey?: string;
            /** Format: date-time */
            uploadedAt: string;
            durationSeconds?: number;
            retakeCount?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            camera?: components["schemas"]["MediaArtifactDto"];
            screen?: components["schemas"]["MediaArtifactDto"];
            behaviorSignals?: components["schemas"]["AnswerBehaviorSignalsDto"];
            selectedVersionNumber?: number;
            transcript?: components["schemas"]["AnswerTranscriptDto"];
            evaluation?: components["schemas"]["AnswerEvaluationDto"];
            validation?: components["schemas"]["AnswerValidationDto"];
            versions?: components["schemas"]["AnswerVersionDto"][];
            behaviorEvents?: components["schemas"]["AnswerBehaviorEventDto"][];
        };
        InterviewBehaviorSummaryDto: {
            /** @enum {string} */
            riskLevel?: "low" | "medium" | "high";
            notes: string[];
        };
        InterviewQuestionResultDto: {
            questionIndex: number;
            questionId: string;
            score?: number;
            categoryScores?: {
                [key: string]: number;
            };
            summary?: string;
            /** @enum {string} */
            decisionHint?: "pass" | "review" | "fail";
        };
        InterviewResultResponseDto: {
            overallScore: number;
            summary: string;
            categoryScores: {
                [key: string]: number;
            };
            rubricVersion?: string;
            /** @enum {string} */
            decision?: "proceed" | "review" | "reject";
            trustScore?: number;
            trustFlags?: string[];
            behaviorSummary?: components["schemas"]["InterviewBehaviorSummaryDto"];
            questionResults?: components["schemas"]["InterviewQuestionResultDto"][];
            /** Format: date-time */
            completedAt: string;
        };
        InterviewWorkflowDto: {
            /** @enum {string} */
            status: "idle" | "queued" | "processing" | "completed" | "failed";
            /** @enum {string} */
            currentStage?: "validate_answers" | "transcribe_audio" | "analyze_answers" | "aggregate_result" | "store_result";
            executionId?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            lastUpdatedAt: string;
            errorMessage?: string;
        };
        InterviewWithCandidateLinkResponseDto: {
            id: string;
            candidateName: string;
            candidateEmail?: string;
            position: string;
            questions: components["schemas"]["QuestionResponseDto"][];
            answers: components["schemas"]["AnswerDto"][];
            /** @enum {string} */
            status: "pending" | "in_progress" | "processing" | "completed" | "failed" | "canceled";
            result?: components["schemas"]["InterviewResultResponseDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            workflow?: components["schemas"]["InterviewWorkflowDto"];
            candidateLink: string;
        };
        InterviewResponseDto: {
            id: string;
            candidateName: string;
            candidateEmail?: string;
            position: string;
            questions: components["schemas"]["QuestionResponseDto"][];
            answers: components["schemas"]["AnswerDto"][];
            /** @enum {string} */
            status: "pending" | "in_progress" | "processing" | "completed" | "failed" | "canceled";
            result?: components["schemas"]["InterviewResultResponseDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            workflow?: components["schemas"]["InterviewWorkflowDto"];
        };
        CandidateLinkResponseDto: {
            candidateLink: string;
        };
        UpdateInterviewDto: {
            candidateName?: string;
            candidateEmail?: string;
            position?: string;
            questionIds?: string[];
        };
        StartAnswerValidationResultDto: {
            /** @enum {string} */
            status: "idle" | "queued" | "processing" | "completed" | "failed";
            questionIndex: number;
            sourceVersionNumber: number;
            reused: boolean;
        };
        StartAllAnswerValidationsResponseDto: {
            /** @example true */
            ok: boolean;
            interviewId: string;
            requestedCount: number;
            queuedCount: number;
            reusedCount: number;
            skippedCount: number;
            answers: components["schemas"]["StartAnswerValidationResultDto"][];
        };
        PresignRequestDto: {
            questionIndex: number;
            /** @enum {string} */
            contentType: "video/webm";
            /** @enum {string} */
            mediaType?: "camera" | "screen";
        };
        PresignedUrlResponseDto: {
            uploadUrl: string;
            mediaKey: string;
        };
        ConfirmUploadDto: {
            questionIndex: number;
            mediaKey: string;
        };
        ConfirmUploadResponseDto: {
            mediaKey: string;
            /** @example true */
            confirmed: boolean;
        };
        StartMultipartUploadDto: {
            questionIndex: number;
            /** @enum {string} */
            contentType: "video/webm";
            /** @enum {string} */
            mediaType?: "camera" | "screen";
        };
        MultipartUploadSessionResponseDto: {
            mediaKey: string;
            uploadId: string;
        };
        PresignMultipartPartDto: {
            questionIndex: number;
            mediaKey: string;
            uploadId: string;
            partNumber: number;
        };
        MultipartUploadPartResponseDto: {
            mediaKey: string;
            uploadId: string;
            partNumber: number;
            uploadUrl: string;
        };
        CompleteMultipartUploadDto: {
            questionIndex: number;
            mediaKey: string;
            uploadId: string;
        };
        MultipartUploadCompleteResponseDto: {
            mediaKey: string;
            uploadId: string;
            /** @example true */
            completed: boolean;
        };
        AbortMultipartUploadDto: {
            questionIndex: number;
            mediaKey: string;
            uploadId: string;
        };
        MultipartUploadAbortResponseDto: {
            mediaKey: string;
            uploadId: string;
            /** @example true */
            aborted: boolean;
        };
        RecruiterPresignUploadBodyDto: {
            /** @enum {string} */
            contentType: "video/webm";
            /** @enum {string} */
            mediaType?: "camera" | "screen";
        };
        RecruiterConfirmUploadBodyDto: {
            mediaKey: string;
        };
        InterviewAnswerMediaResponseDto: {
            questionIndex: number;
            cameraUrl?: string;
            screenUrl?: string;
        };
        HealthResponseDto: {
            /** @example ok */
            status: string;
            /**
             * Format: date-time
             * @example 2026-05-05T12:00:00.000Z
             */
            timestamp: string;
        };
        CandidateQuestionViewDto: {
            text: string;
        };
        CurrentAnswerMetaDto: {
            /** @enum {string} */
            status: "recording" | "submitted";
            versionCount: number;
            selectedVersionNumber: number;
        };
        TakeInterviewResponseDto: {
            id: string;
            position: string;
            candidateName: string;
            status: string;
            totalQuestions: number;
            currentQuestion?: components["schemas"]["CandidateQuestionViewDto"];
            currentQuestionIndex: number;
            currentAnswerMeta?: components["schemas"]["CurrentAnswerMetaDto"];
            completed: boolean;
        };
        BehaviorSignalsDto: {
            /** @default 0 */
            tabHiddenCount: number;
            /** @default 0 */
            windowBlurCount: number;
            /** @default 0 */
            pasteCount: number;
            /** @default 0 */
            keydownCount: number;
            /** @default 0 */
            copyCount: number;
            /** @default 0 */
            resizeCount: number;
        };
        BehaviorEventDto: {
            /** @enum {string} */
            eventType: "tab_hidden" | "window_blur" | "copy" | "paste" | "keydown" | "resize";
            /** Format: date-time */
            occurredAt: string;
            versionNumber: number;
        };
        ClientTranscriptDto: {
            text: string;
            language: string;
            provider: string;
            /** Format: date-time */
            generatedAt: string;
            isFinal: boolean;
        };
        SubmitAnswerDto: {
            questionIndex: number;
            versionNumber: number;
            submitAnswer: boolean;
            mediaKey: string;
            screenMediaKey?: string;
            durationSeconds: number;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            submittedAt: string;
            cameraFileSizeBytes?: number;
            screenFileSizeBytes?: number;
            behaviorSignals: components["schemas"]["BehaviorSignalsDto"];
            behaviorEvents?: components["schemas"]["BehaviorEventDto"][];
            clientTranscript?: components["schemas"]["ClientTranscriptDto"];
        };
        SubmitTakeAnswerResponseDto: {
            /** @example true */
            ok: boolean;
            answeredCount: number;
            totalQuestions: number;
            completed: boolean;
        };
        SaveAnswerProgressDto: {
            questionIndex: number;
            versionNumber: number;
            mediaKey: string;
            screenMediaKey?: string;
            durationSeconds?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            cameraFileSizeBytes?: number;
            screenFileSizeBytes?: number;
            behaviorSignals: components["schemas"]["BehaviorSignalsDto"];
            behaviorEvents?: components["schemas"]["BehaviorEventDto"][];
            clientTranscript?: components["schemas"]["ClientTranscriptDto"];
        };
        SaveTakeAnswerProgressResponseDto: {
            /** @example true */
            ok: boolean;
            /** @enum {string} */
            status: "recording" | "submitted";
            versionCount: number;
            selectedVersionNumber: number;
        };
        StartTakeAnswerValidationResponseDto: {
            /** @example true */
            ok: boolean;
            /** @enum {string} */
            status: "idle" | "queued" | "processing" | "completed" | "failed";
            questionIndex: number;
            sourceVersionNumber: number;
            reused: boolean;
        };
        ChatHistoryItemDto: {
            /** @enum {string} */
            role: "system" | "assistant" | "candidate";
            content: string;
        };
        ChatDto: {
            question: string;
            position: string;
            candidateName: string;
            history: components["schemas"]["ChatHistoryItemDto"][];
            message: string;
        };
        AiTextResponseDto: {
            response: string;
        };
        GreetDto: {
            candidateName: string;
            position: string;
            totalQuestions: number;
        };
        DraftQuestionDto: {
            question?: components["schemas"]["CreateQuestionDto"];
        };
        QuestionDraftResponseDto: {
            externalId?: string;
            role?: string;
            focus?: string;
            outputLanguage: string;
            category?: string;
            subcategory?: string;
            questionText: string;
            followUpQuestions: string[];
            expectedConcepts: components["schemas"]["QuestionExpectedConceptDto"][];
            redFlags: components["schemas"]["QuestionRedFlagDto"][];
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            weight: number;
            sampleGoodAnswer?: string;
            minimumPassScore: number;
            tags: string[];
            metadata: {
                [key: string]: unknown;
            };
        };
        FeedbackResponseDto: {
            position: string;
            date: string;
            expiresAt: string;
            /** @enum {string} */
            overallResult?: "pass" | "borderline" | "fail";
            overallScore?: number;
            categoryScores?: {
                [key: string]: number;
            };
            generalFeedback?: string;
            improvements?: string;
        };
        FeedbackLinkResponseDto: {
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many login attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"];
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google OAuth consent screen */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sets session cookie and redirects to frontend */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"];
                };
            };
            /** @description Missing or invalid session cookie */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_list: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UserController_assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_findAll: {
        parameters: {
            query?: {
                /** @description Free-text search over question text, role, category, subcategory, tags. */
                q?: string;
                difficulty?: "easy" | "medium" | "hard";
                category?: string;
                /** @description Subcategory — exposed as the "Type" filter in the picker UI. */
                subcategory?: string;
                /** @description ANY-match: rows whose tags array overlaps the given list. Send as ?tags=react,hooks or repeated. */
                tags?: string[];
                role?: string;
                outputLanguage?: string;
                /** @description Non-super_admin callers are forced to "active" regardless of what they pass. */
                status?: "active" | "inactive" | "all" | "scheduled";
                sortBy?: "createdAt" | "updatedAt" | "difficulty" | "questionText" | "popularity";
                sortOrder?: "asc" | "desc";
                page?: number;
                limit?: number;
                /** @description When true, only interview-eligible (active) questions are returned */
                eligibleForInterview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedQuestionsResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_getFacets: {
        parameters: {
            query?: {
                /** @description Free-text search over question text, role, category, subcategory, tags. */
                q?: string;
                difficulty?: "easy" | "medium" | "hard";
                category?: string;
                /** @description Subcategory — exposed as the "Type" filter in the picker UI. */
                subcategory?: string;
                /** @description ANY-match: rows whose tags array overlaps the given list. Send as ?tags=react,hooks or repeated. */
                tags?: string[];
                role?: string;
                outputLanguage?: string;
                /** @description Non-super_admin callers are forced to "active" regardless of what they pass. */
                status?: "active" | "inactive" | "all" | "scheduled";
                sortBy?: "createdAt" | "updatedAt" | "difficulty" | "questionText" | "popularity";
                sortOrder?: "asc" | "desc";
                page?: number;
                limit?: number;
                /** @description When true, only interview-eligible (active) questions are returned */
                eligibleForInterview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionFacetsResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteQuestionResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_findSimilar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindSimilarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindSimilarResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_bulkRemove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteQuestionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteQuestionsResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    QuestionController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponseDto"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewWithCandidateLinkResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInterviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_generateCandidateLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateLinkResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_validateAllAnswers: {
        parameters: {
            query?: {
                /** @description Re-evaluate answers whose latest validation already completed. Defaults to false; in-flight validations always return 409. */
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAllAnswerValidationsResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_validateAnswer: {
        parameters: {
            query?: {
                /** @description Re-evaluate the answer if its latest validation already completed. Defaults to false; in-flight validations always return 409. */
                force?: boolean;
            };
            header?: never;
            path: {
                id: string;
                questionIndex: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAnswerValidationResultDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    InterviewController_getResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResultResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmUploadResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_startMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartMultipartUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipartUploadSessionResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_presignMultipartPart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignMultipartPartDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipartUploadPartResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_completeMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteMultipartUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipartUploadCompleteResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UploadController_abortMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbortMultipartUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipartUploadAbortResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    RecruiterMediaController_presignManualUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionIndex: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruiterPresignUploadBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    RecruiterMediaController_completeManualUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionIndex: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecruiterConfirmUploadBodyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmUploadResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    RecruiterMediaController_getAnswerMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionIndex: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewAnswerMediaResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    TakeController_getInterview: {
        parameters: {
            query?: {
                token?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TakeInterviewResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TakeController_submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitTakeAnswerResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TakeController_saveAnswerProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerProgressDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveTakeAnswerProgressResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TakeController_startAnswerValidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionIndex: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartTakeAnswerValidationResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AiController_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTextResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AiController_greet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GreetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTextResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AiController_draftQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftQuestionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDraftResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    FeedbackController_getFeedback: {
        parameters: {
            query: {
                /** @description Access token from the share link */
                token: string;
            };
            header?: never;
            path: {
                /** @description Interview ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    FeedbackLinkController_createLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackLinkResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    FeedbackLinkController_revokeLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Interview ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link successfully revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
}
