import type { OnboardingFlowConfig } from '@/features/onboarding/types';

export const staffFirstLoginFlow: OnboardingFlowConfig = {
  id: 'staff-first-login',
  steps: [
    {
      id: 'dashboard-hero',
      route: '/',
      target: '[data-tour="dashboard-hero"]',
      contentKey: 'dashboardHero',
      missingTarget: 'wait',
      waitTimeoutMs: 3000,
      popoverSide: 'bottom',
      popoverAlign: 'start',
    },
    {
      id: 'questions-library',
      route: '/questions',
      target: '[data-tour="questions-library"]',
      contentKey: 'questionsPage',
      visibility: [{ type: 'canReadQuestions' }],
      missingTarget: 'wait',
      waitTimeoutMs: 5000,
      popoverSide: 'bottom',
      popoverAlign: 'start',
    },
    {
      id: 'assessments-list',
      route: '/assessments',
      target: '[data-tour="assessments-list"]',
      contentKey: 'assessmentsPage',
      visibility: [{ type: 'canReviewAssessments' }],
      missingTarget: 'wait',
      waitTimeoutMs: 5000,
      popoverSide: 'bottom',
      popoverAlign: 'start',
    },
    {
      id: 'interview-create',
      route: '/interviews/new',
      target: '[data-tour="interview-create"]',
      contentKey: 'newInterviewPage',
      visibility: [{ type: 'canConfigureInterview' }],
      missingTarget: 'wait',
      waitTimeoutMs: 5000,
      popoverSide: 'bottom',
      popoverAlign: 'start',
    },
    {
      id: 'team-members',
      route: '/team',
      target: '[data-tour="team-members"]',
      contentKey: 'teamPage',
      visibility: [{ type: 'canManageTeam' }],
      missingTarget: 'wait',
      waitTimeoutMs: 5000,
      popoverSide: 'bottom',
      popoverAlign: 'start',
    },
  ],
};
