import type { OnboardingFlowConfig, OnboardingStepConfig } from '@/features/onboarding/types';
import { ONBOARDING_EVENT_NAMES } from '@/features/onboarding/onboarding-events';

const pageTourStepDefaults = {
  missingTarget: 'wait',
  waitTimeoutMs: 5000,
  popoverSide: 'bottom',
  popoverAlign: 'start',
} as const satisfies Partial<OnboardingStepConfig>;

export const staffFirstLoginFlow: OnboardingFlowConfig = {
  id: 'staff-first-login',
  steps: [
    {
      id: 'dashboard-hero',
      route: '/',
      target: '[data-tour="dashboard-hero"]',
      contentKey: 'dashboardHero',
      ...pageTourStepDefaults,
    },
    {
      id: 'questions-library',
      route: '/questions',
      target: '[data-tour="questions-library"]',
      contentKey: 'questionsLibrary',
      visibility: [{ type: 'canReadQuestions' }],
      ...pageTourStepDefaults,
    },
    {
      id: 'questions-create',
      route: '/questions/new',
      target: '[data-tour="question-text"]',
      contentKey: 'questionsText',
      visibility: [{ type: 'canReadQuestions' }, { type: 'notDemo' }],
      gate: { type: 'nonEmptyInput', autoFocus: true },
      ...pageTourStepDefaults,
      stageRadius: 24,
      popoverSide: 'top',
      popoverAlign: 'start',
    },
    {
      id: 'questions-ai-draft',
      route: '/questions/new',
      target: '[data-tour="ai-draft-panel"]',
      contentKey: 'questionsAiDraft',
      visibility: [{ type: 'canReadQuestions' }, { type: 'notDemo' }],
      advance: {
        mode: 'event',
        eventName: ONBOARDING_EVENT_NAMES.aiDraftGenerated,
      },
      ...pageTourStepDefaults,
      popoverSide: 'left',
      popoverAlign: 'start',
    },
    {
      id: 'questions-ai-apply',
      route: '/questions/new',
      target: '[data-tour="ai-draft-panel"]',
      contentKey: 'questionsAiApply',
      visibility: [{ type: 'canReadQuestions' }, { type: 'notDemo' }],
      advance: {
        mode: 'event',
        eventName: ONBOARDING_EVENT_NAMES.aiDraftApplied,
      },
      ...pageTourStepDefaults,
      waitTimeoutMs: 8000,
      popoverSide: 'left',
      popoverAlign: 'start',
      mobile: {
        scrollIntoViewBlock: 'start',
      },
    },
    {
      id: 'questions-save',
      route: '/questions/new',
      target: '[data-tour="question-save-bar"]',
      contentKey: 'questionsCreate',
      visibility: [{ type: 'canReadQuestions' }, { type: 'notDemo' }],
      advance: {
        mode: 'event',
        eventName: ONBOARDING_EVENT_NAMES.questionCreated,
      },
      ...pageTourStepDefaults,
      popoverSide: 'top',
      popoverAlign: 'end',
    },
    {
      id: 'interview-select',
      route: '/interviews/new',
      target: '[data-tour="interview-question"]',
      contentKey: 'interviewPicker',
      visibility: [{ type: 'canConfigureInterview' }, { type: 'notDemo' }],
      advance: {
        mode: 'event',
        eventName: ONBOARDING_EVENT_NAMES.questionSelected,
      },
      ...pageTourStepDefaults,
      preservePageTop: true,
      pageScrollTop: 190,
      popoverSide: 'top',
      popoverAlign: 'start',
      mobile: {
        preservePageTop: undefined,
        pageScrollTop: undefined,
        waitTimeoutMs: 8000,
        scrollIntoViewBlock: 'center',
        lockPopoverPlacement: 'bottom-start',
        popoverSide: 'bottom',
        popoverAlign: 'start',
      },
    },
    {
      id: 'interview-candidate',
      route: '/interviews/new',
      target: '[data-tour="interview-candidate"]',
      contentKey: 'interviewCandidate',
      visibility: [{ type: 'canConfigureInterview' }, { type: 'notDemo' }],
      advance: {
        mode: 'event',
        eventName: ONBOARDING_EVENT_NAMES.interviewCreated,
      },
      ...pageTourStepDefaults,
      preservePageTop: true,
      pageScrollTop: 190,
      popoverSide: 'right',
      popoverAlign: 'start',
      mobile: {
        preservePageTop: undefined,
        pageScrollTop: undefined,
        scrollIntoViewBlock: 'start',
        lockPopoverPlacement: 'bottom-start',
        popoverSide: 'bottom',
        popoverAlign: 'start',
      },
    },
    {
      id: 'candidate-link',
      route: '/interviews',
      routeMatch: 'prefix',
      target: '[data-tour="candidate-link"]',
      contentKey: 'candidateLink',
      visibility: [{ type: 'canConfigureInterview' }, { type: 'notDemo' }],
      ...pageTourStepDefaults,
      waitTimeoutMs: 8000,
      lockPopoverPlacement: 'bottom-end',
      popoverSide: 'bottom',
      popoverAlign: 'end',
    },
    {
      id: 'assessments-evaluation',
      route: '/assessments',
      target: '[data-tour="assessments-card"]',
      contentKey: 'assessmentsEvaluation',
      visibility: [{ type: 'canReviewAssessments' }, { type: 'notDemo' }],
      ...pageTourStepDefaults,
      waitTimeoutMs: 8000,
      scrollIntoViewBlock: 'center',
      popoverSide: 'right',
      popoverAlign: 'start',
    },
  ],
};
