import type { Interview } from '@/lib/api'

function mockQuestion(
  id: string,
  questionText: string,
  expectedConceptLabels: string[],
  redFlagLabels: string[],
  difficulty: 'easy' | 'medium' | 'hard',
  weight: number,
) {
  const now = new Date().toISOString()
  return {
    id,
    role: 'frontend intern',
    focus: 'fundamentals',
    outputLanguage: 'English',
    category: 'soft_skills',
    subcategory: 'fundamentals',
    questionText,
    followUpQuestions: [],
    expectedConcepts: expectedConceptLabels.map((label, index) => ({
      id: `${id}_concept_${index + 1}`,
      label,
      weight: Number((1 / expectedConceptLabels.length).toFixed(4)),
      description: `${label} should be covered in the answer.`,
    })),
    redFlags: redFlagLabels.map((label, index) => ({
      id: `${id}_flag_${index + 1}`,
      label,
      severity: 'medium' as const,
    })),
    difficulty,
    weight,
    sampleGoodAnswer: '',
    minimumPassScore: difficulty === 'hard' ? 3.5 : difficulty === 'medium' ? 3 : 2.5,
    tags: [],
    metadata: {},
    createdAt: now,
    updatedAt: now,
    deleted: false,
    pendingDeletion: false,
    usageCount: 0,
  }
}

export const DASHBOARD_MOCK_INTERVIEWS: Interview[] = [
  {
    id: 'mock-11',
    candidateName: 'Alice Johnson',
    position: 'Senior Frontend Engineer',
    questions: [
      mockQuestion(
        'mock-1-q1',
        'Tell me about yourself',
        ['relevant experience', 'clear structure'],
        ['too generic'],
        'easy',
        1,
      ),
      mockQuestion(
        'mock-1-q2',
        'Describe a challenging project',
        ['ownership', 'trade-offs', 'result'],
        ['no measurable outcome'],
        'medium',
        2,
      ),
    ],
    answers: [],
    status: 'pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    candidateName: 'Bob Smith',
    position: 'Backend Developer',
    questions: [
      mockQuestion(
        'mock-2-q1',
        'Why this role?',
        ['motivation', 'role alignment'],
        ['generic motivation'],
        'easy',
        1,
      ),
      mockQuestion(
        'mock-2-q2',
        'System design experience?',
        ['scalability', 'trade-offs'],
        ['no constraints discussion'],
        'hard',
        3,
      ),
    ],
    answers: [
      {
        questionIndex: 0,
        questionId: 'mock-2-q1',
        status: 'submitted',
        mediaKey: 's3://mock-camera',
        screenMediaKey: 's3://mock-screen',
        uploadedAt: new Date().toISOString(),
      },
    ],
    status: 'in_progress',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    candidateName: 'Carol Lee',
    position: 'Full Stack Engineer',
    questions: [
      mockQuestion(
        'mock-3-q1',
        'Strengths?',
        ['self-awareness', 'evidence'],
        ['buzzwords only'],
        'easy',
        1,
      ),
      mockQuestion(
        'mock-3-q2',
        'Weaknesses?',
        ['reflection', 'improvement plan'],
        ['fake weakness'],
        'easy',
        1,
      ),
      mockQuestion(
        'mock-3-q3',
        'Where do you see yourself in 5 years?',
        ['career direction', 'role fit'],
        ['no alignment with role'],
        'easy',
        1,
      ),
    ],
    answers: [],
    status: 'completed',
    result: {
      overallScore: 82,
      summary: 'Strong candidate with good communication skills.',
      categoryScores: { technical: 85, communication: 80, problemSolving: 81 },
      completedAt: new Date().toISOString(),
    },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
